services:
  app:
    build:
      context: ./app
      args:
        - VITE_API_URL=http://api:8080
    depends_on:
      mongodb:
        condition: service_healthy
      api:
        condition: service_started
    ports:
      - 5173:5173
  api:
    build: ./api
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_CONN=mongodb://user:pass@mongodb
    ports:
      - 8080:8080
  mongodb:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s